import { PublicPageContent } from '../components/PublicPageTemplate';

export const publicPageContent: Record<string, PublicPageContent> = {
  membership: {
    eyebrow: 'Membership',
    title: 'Membership That Turns Participation Into Opportunity',
    subtitle: 'Choose the right membership path, unlock rewards, and connect with programs aligned to your goals.',
    tone: 'blue',
    metrics: [
      { label: 'Active Members', value: '300K+' },
      { label: 'Monthly Rewards', value: '2.4M pts' },
      { label: 'Events Accessed', value: '340+' },
      { label: 'Partner Discounts', value: '860+' },
    ],
    focusAreas: [
      { title: 'Membership Packages', description: 'Compare tiers and pick the level that fits your growth pace.' },
      { title: 'Points & Rewards', description: 'Earn through events, referrals, and marketplace activities.' },
      { title: 'Member Benefits', description: 'Access premium offers, networking circles, and community programs.' },
      { title: 'Recognition', description: 'Get featured through monthly top member and impact-based rankings.' },
    ],
    quickLinks: [
      { label: 'View Events', path: '/events' },
      { label: 'Explore Offers', path: '/offer' },
      { label: 'Browse Products', path: '/product' },
      { label: 'Join Now', path: '/auth' },
    ],
    steps: [
      'Select your membership plan and complete your profile.',
      'Join events and services to begin earning activity points.',
      'Track leaderboard, rewards, and unlock premium benefits.',
      'Use your profile to network with partners and franchises.',
    ],
    cta: {
      title: 'Ready to become a member?',
      subtitle: 'Create your account and activate your membership journey today.',
      primary: { label: 'Create Account', path: '/auth' },
      secondary: { label: 'Contact Team', path: '/contact' },
    },
  },
  partner: {
    eyebrow: 'Partner',
    title: 'Partnership Programs Built for Sustainable Growth',
    subtitle: 'Join as a strategic partner to co-create offers, host events, and reach high-intent members.',
    tone: 'indigo',
    metrics: [
      { label: 'Partner Brands', value: '860+' },
      { label: 'Co-hosted Events', value: '340+' },
      { label: 'Partner Leads', value: '52K+' },
      { label: 'Satisfaction', value: '4.8/5' },
    ],
    focusAreas: [
      { title: 'Partner Onboarding', description: 'Structured setup with profile verification and category mapping.' },
      { title: 'Campaign Collaboration', description: 'Launch bundled offers and event-led campaigns with measurable impact.' },
      { title: 'Performance Insights', description: 'Track clicks, leads, conversions, and audience engagement.' },
      { title: 'Account Support', description: 'Dedicated relationship support for scaling your partnership.' },
    ],
    quickLinks: [
      { label: 'View Franchise Opportunities', path: '/franchise' },
      { label: 'See Events', path: '/events' },
      { label: 'Explore Services', path: '/services' },
      { label: 'Apply as Partner', path: '/auth' },
    ],
    steps: [
      'Submit your business profile and compliance details.',
      'Pick partner categories and launch your first campaign.',
      'Publish offers, events, and product listings for members.',
      'Review monthly analytics and optimize performance.',
    ],
    cta: {
      title: 'Start your partner application',
      subtitle: 'Get listed, launch programs, and grow with the E-SPOT ecosystem.',
      primary: { label: 'Apply as Partner', path: '/auth' },
      secondary: { label: 'Talk to Partnerships', path: '/contact' },
    },
  },
  franchise: {
    eyebrow: 'Franchise',
    title: 'Franchise Expansion With Proven Operational Playbooks',
    subtitle: 'Open local E-SPOT franchise operations with training, branding support, and demand channels.',
    tone: 'amber',
    metrics: [
      { label: 'Franchise Units', value: '120+' },
      { label: 'Cities', value: '45+' },
      { label: 'Avg Rating', value: '4.8/5' },
      { label: 'Support Coverage', value: '24/7' },
    ],
    focusAreas: [
      { title: 'Location Planning', description: 'Market and catchment analysis before launch approval.' },
      { title: 'Operations Setup', description: 'SOPs, staffing templates, and service standards from day one.' },
      { title: 'Brand Activation', description: 'Launch kits, local marketing assets, and opening campaigns.' },
      { title: 'Franchise Growth', description: 'Quarterly targets with performance coaching and reviews.' },
    ],
    quickLinks: [
      { label: 'Partner Programs', path: '/partner' },
      { label: 'Training Module', path: '/training' },
      { label: 'Contact Team', path: '/contact' },
      { label: 'Start Application', path: '/auth' },
    ],
    steps: [
      'Submit your franchise intent and preferred market.',
      'Complete business review and location validation.',
      'Finish onboarding and operator training.',
      'Launch your branch with central promotion support.',
    ],
    cta: {
      title: 'Open your franchise with confidence',
      subtitle: 'Build a profitable local operation with a proven network model.',
      primary: { label: 'Apply for Franchise', path: '/auth' },
      secondary: { label: 'Book Consultation', path: '/contact' },
    },
  },
  careers: {
    eyebrow: 'Careers',
    title: 'Careers Across Services, Events, and Platform Teams',
    subtitle: 'Find roles in operations, programs, technology, and customer experience across E-SPOT units.',
    tone: 'slate',
    metrics: [
      { label: 'Open Roles', value: '42' },
      { label: 'Teams Hiring', value: '12' },
      { label: 'Remote Friendly', value: '65%' },
      { label: 'Avg Hiring Time', value: '21 days' },
    ],
    focusAreas: [
      { title: 'Operations Roles', description: 'Drive service quality in travel, events, and franchise operations.' },
      { title: 'Platform Roles', description: 'Build digital products that support member and partner growth.' },
      { title: 'Creative Roles', description: 'Own brand, content, and multimedia storytelling initiatives.' },
      { title: 'Leadership Roles', description: 'Lead teams and shape strategic execution across verticals.' },
    ],
    quickLinks: [
      { label: 'Training & Upskilling', path: '/training' },
      { label: 'Leadership Programs', path: '/leadership' },
      { label: 'Contact HR', path: '/contact' },
      { label: 'Apply Now', path: '/auth' },
    ],
    steps: [
      'Explore role families and open positions.',
      'Submit application with relevant work samples.',
      'Complete role interview and practical evaluation.',
      'Join onboarding with team-specific learning plan.',
    ],
    cta: {
      title: 'Find your next role at E-SPOT',
      subtitle: 'Apply to current openings or share your profile for future opportunities.',
      primary: { label: 'Apply Through Portal', path: '/auth' },
      secondary: { label: 'Contact HR Team', path: '/contact' },
    },
  },
  training: {
    eyebrow: 'Training',
    title: 'Training, Jobs, and Career Pathways in One Place',
    subtitle: 'Upskill with structured programs and move directly into opportunities across the network.',
    tone: 'blue',
    metrics: [
      { label: 'Courses', value: '180+' },
      { label: 'Certified Trainers', value: '95+' },
      { label: 'Placements', value: '4.2K' },
      { label: 'Job Listings', value: '1.1K' },
    ],
    focusAreas: [
      { title: 'Skill Tracks', description: 'Role-based learning tracks for business, tech, and operations.' },
      { title: 'Trainer Network', description: 'Learn from expert mentors with domain-specific experience.' },
      { title: 'Talent Discovery', description: 'Build portfolio visibility and connect with hiring partners.' },
      { title: 'Career Services', description: 'Interview prep, CV feedback, and job-matching support.' },
    ],
    quickLinks: [
      { label: 'Browse Careers', path: '/careers' },
      { label: 'Entrepreneurship', path: '/entrepreneurship' },
      { label: 'Profiles', path: '/profiles' },
      { label: 'Join Program', path: '/auth' },
    ],
    steps: [
      'Pick your learning pathway based on target role.',
      'Complete modules, assignments, and evaluations.',
      'Showcase proof-of-work in your profile.',
      'Apply to matching jobs and partner openings.',
    ],
    cta: {
      title: 'Start upskilling this week',
      subtitle: 'Move from learning to placement with guided career support.',
      primary: { label: 'Join Training', path: '/auth' },
      secondary: { label: 'Explore Careers', path: '/careers' },
    },
  },
  scholar: {
    eyebrow: 'Scholar',
    title: 'Scholarship and Education Support Programs',
    subtitle: 'Access scholarship opportunities, connect with institutions, and track educational milestones.',
    tone: 'emerald',
    metrics: [
      { label: 'Scholarships', value: '75+' },
      { label: 'Institutions', value: '40+' },
      { label: 'Scholars Funded', value: '2.3K' },
      { label: 'Donor Partners', value: '120+' },
    ],
    focusAreas: [
      { title: 'Funding Discovery', description: 'Filter scholarships by eligibility, deadline, and category.' },
      { title: 'Institution Matching', description: 'Find programs aligned to your field and outcome goals.' },
      { title: 'Application Guidance', description: 'Step-by-step support for stronger scholarship applications.' },
      { title: 'Progress Tracking', description: 'Monitor milestones, deadlines, and review statuses.' },
    ],
    quickLinks: [
      { label: 'Leadership Program', path: '/leadership' },
      { label: 'Training Module', path: '/training' },
      { label: 'Contact Support', path: '/contact' },
      { label: 'Apply as Scholar', path: '/auth' },
    ],
    steps: [
      'Build scholar profile with academic details.',
      'Shortlist relevant opportunities and deadlines.',
      'Submit applications with required documents.',
      'Track acceptance and onboarding to programs.',
    ],
    cta: {
      title: 'Apply for scholarship opportunities',
      subtitle: 'Get matched to programs that fit your education journey.',
      primary: { label: 'Start Scholar Profile', path: '/auth' },
      secondary: { label: 'Contact Scholar Desk', path: '/contact' },
    },
  },
  leadership: {
    eyebrow: 'Leadership',
    title: 'Leadership Programs for Emerging and Senior Professionals',
    subtitle: 'Develop strategic thinking, execution capability, and team influence through structured programs.',
    tone: 'indigo',
    metrics: [
      { label: 'Workshops', value: '60+' },
      { label: 'Mentors', value: '85+' },
      { label: 'Leaders Trained', value: '9.4K' },
      { label: 'Avg Program Score', value: '4.9/5' },
    ],
    focusAreas: [
      { title: 'Leadership Essentials', description: 'Decision-making, communication, and organizational alignment.' },
      { title: 'Advanced Labs', description: 'Scenario-led training for growth, conflict, and change leadership.' },
      { title: 'Mentor Circles', description: 'Peer and mentor sessions with practical feedback loops.' },
      { title: 'Execution Coaching', description: 'Program-based accountability for real business outcomes.' },
    ],
    quickLinks: [
      { label: 'Training Programs', path: '/training' },
      { label: 'Entrepreneurship', path: '/entrepreneurship' },
      { label: 'Events', path: '/events' },
      { label: 'Enroll', path: '/auth' },
    ],
    steps: [
      'Choose leadership path by role and experience level.',
      'Attend workshops and complete applied case tasks.',
      'Join mentor circles for coaching and reflection.',
      'Graduate with portfolio-ready leadership outcomes.',
    ],
    cta: {
      title: 'Enroll in leadership tracks',
      subtitle: 'Build influence and execution confidence with guided programs.',
      primary: { label: 'Enroll Now', path: '/auth' },
      secondary: { label: 'View Events', path: '/events' },
    },
  },
  product: {
    eyebrow: 'Product',
    title: 'Product Marketplace Curated for Members and Partners',
    subtitle: 'Discover trusted products, compare value, and buy through verified network vendors.',
    tone: 'slate',
    metrics: [
      { label: 'Listed Products', value: '4.8K' },
      { label: 'Verified Vendors', value: '860+' },
      { label: 'Avg Rating', value: '4.7/5' },
      { label: 'Monthly Orders', value: '12K+' },
    ],
    focusAreas: [
      { title: 'Category Browsing', description: 'Explore product categories aligned to member demand.' },
      { title: 'Vendor Trust', description: 'Buy from verified partners with quality standards.' },
      { title: 'Member Pricing', description: 'Unlock pricing tiers tied to your membership level.' },
      { title: 'Post-purchase Support', description: 'Track deliveries and resolve queries through support channels.' },
    ],
    quickLinks: [
      { label: 'Current Offers', path: '/offer' },
      { label: 'Partner Program', path: '/partner' },
      { label: 'Showcase', path: '/showcase' },
      { label: 'Get Started', path: '/auth' },
    ],
    steps: [
      'Search by category, vendor, or use case.',
      'Compare options and member-only prices.',
      'Place secure order through verified vendor channels.',
      'Track fulfillment and submit product feedback.',
    ],
    cta: {
      title: 'Explore trusted products today',
      subtitle: 'Shop high-quality listings from verified ecosystem vendors.',
      primary: { label: 'Browse Offers', path: '/offer' },
      secondary: { label: 'Become Vendor', path: '/partner' },
    },
  },
  showcase: {
    eyebrow: 'Showcase',
    title: 'Showcase Success Stories, Work, and Community Highlights',
    subtitle: 'Feature top members, partner campaigns, and franchise performance to build visibility and trust.',
    tone: 'rose',
    metrics: [
      { label: 'Stories Published', value: '1.3K' },
      { label: 'Featured Partners', value: '310+' },
      { label: 'Monthly Views', value: '420K' },
      { label: 'Engagement Rate', value: '18%' },
    ],
    focusAreas: [
      { title: 'Top Performer Spotlights', description: 'Highlight member, partner, and franchise achievements.' },
      { title: 'Campaign Stories', description: 'Publish outcomes from events and business collaborations.' },
      { title: 'Media Gallery', description: 'Share approved visual content from programs and milestones.' },
      { title: 'Trust Building', description: 'Use verified achievements to strengthen brand credibility.' },
    ],
    quickLinks: [
      { label: 'Profiles Directory', path: '/profiles' },
      { label: 'Events Calendar', path: '/events' },
      { label: 'Partner Program', path: '/partner' },
      { label: 'Submit Story', path: '/contact' },
    ],
    steps: [
      'Nominate stories, wins, or campaign outcomes.',
      'Submit content assets and approval details.',
      'Publish through showcase channels and categories.',
      'Track views and audience engagement metrics.',
    ],
    cta: {
      title: 'Publish your success story',
      subtitle: 'Increase visibility for your work across the E-SPOT community.',
      primary: { label: 'Submit for Showcase', path: '/contact' },
      secondary: { label: 'View Profiles', path: '/profiles' },
    },
  },
  offer: {
    eyebrow: 'Offer',
    title: 'Offers Designed to Increase Value for Members',
    subtitle: 'Access seasonal campaigns, partner-led deals, and category-specific discounts.',
    tone: 'amber',
    metrics: [
      { label: 'Live Offers', value: '520+' },
      { label: 'Avg Savings', value: '32%' },
      { label: 'Redeemed Deals', value: '38K+' },
      { label: 'Campaign Partners', value: '260+' },
    ],
    focusAreas: [
      { title: 'Member-only Discounts', description: 'Unlock offer tiers by membership level and activity points.' },
      { title: 'Flash Campaigns', description: 'Short-window high-value promotions across top categories.' },
      { title: 'Partner Promotions', description: 'Discover cross-brand campaigns and bundled value deals.' },
      { title: 'Offer Tracking', description: 'Monitor redemption status and campaign expiry timelines.' },
    ],
    quickLinks: [
      { label: 'Browse Products', path: '/product' },
      { label: 'Membership Plans', path: '/membership' },
      { label: 'Services', path: '/services' },
      { label: 'Claim Access', path: '/auth' },
    ],
    steps: [
      'Browse offers by category or urgency.',
      'Check eligibility based on profile tier.',
      'Redeem and use with partner checkout instructions.',
      'Rate offer quality to improve future curation.',
    ],
    cta: {
      title: 'Activate your next offer',
      subtitle: 'Use your account benefits to unlock better value across categories.',
      primary: { label: 'View Membership', path: '/membership' },
      secondary: { label: 'See Products', path: '/product' },
    },
  },
  entrepreneurship: {
    eyebrow: 'Entrepreneurship',
    title: 'Entrepreneurship Support From Idea to Market Execution',
    subtitle: 'Build ventures with mentorship, pitch opportunities, and partner-market access.',
    tone: 'indigo',
    metrics: [
      { label: 'Startups Supported', value: '980+' },
      { label: 'Mentors', value: '140+' },
      { label: 'Pitch Sessions', value: '210+' },
      { label: 'Funding Introductions', value: '$8.2M' },
    ],
    focusAreas: [
      { title: 'Startup Mentorship', description: 'Get guidance on product, GTM, and growth execution.' },
      { title: 'Pitch Readiness', description: 'Prepare decks, storytelling, and investor communication.' },
      { title: 'Market Access', description: 'Launch through partner channels and community demand loops.' },
      { title: 'Founder Network', description: 'Connect with peers and leaders for faster learning cycles.' },
    ],
    quickLinks: [
      { label: 'Leadership Program', path: '/leadership' },
      { label: 'Training Tracks', path: '/training' },
      { label: 'Events', path: '/events' },
      { label: 'Apply Program', path: '/auth' },
    ],
    steps: [
      'Submit your venture stage and objective.',
      'Join mentor sessions and milestone planning.',
      'Validate market fit via pilot campaigns.',
      'Pitch to ecosystem stakeholders and partners.',
    ],
    cta: {
      title: 'Build your venture with E-SPOT',
      subtitle: 'Join entrepreneurship tracks tailored to your startup stage.',
      primary: { label: 'Join Program', path: '/auth' },
      secondary: { label: 'Contact Program Team', path: '/contact' },
    },
  },
  profiles: {
    eyebrow: 'Profiles',
    title: 'Profiles Directory for Members, Partners, and Franchises',
    subtitle: 'Find verified profiles, compare capabilities, and connect with relevant people and organizations.',
    tone: 'slate',
    metrics: [
      { label: 'Total Profiles', value: '300K+' },
      { label: 'Verified Accounts', value: '92%' },
      { label: 'Partner Profiles', value: '860+' },
      { label: 'Franchise Profiles', value: '120+' },
    ],
    focusAreas: [
      { title: 'Discovery', description: 'Search by role, expertise, category, and location.' },
      { title: 'Verification', description: 'Prioritize trusted profiles with validation badges.' },
      { title: 'Connection Paths', description: 'Reach out through context-aware profile actions.' },
      { title: 'Profile Highlights', description: 'View achievements, offerings, and activity history.' },
    ],
    quickLinks: [
      { label: 'Partner Directory', path: '/partner' },
      { label: 'Franchise Profiles', path: '/franchise' },
      { label: 'User Search', path: '/search' },
      { label: 'Complete Your Profile', path: '/auth' },
    ],
    steps: [
      'Use search filters to narrow profile matches.',
      'Review verification and profile performance indicators.',
      'Shortlist and connect with relevant profiles.',
      'Track interactions and collaboration opportunities.',
    ],
    cta: {
      title: 'Find the right people faster',
      subtitle: 'Use profile intelligence to connect with value-aligned contacts.',
      primary: { label: 'Search Profiles', path: '/search' },
      secondary: { label: 'Create Profile', path: '/auth' },
    },
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Get Support for Membership, Partnerships, and Programs',
    subtitle: 'Reach the right team for onboarding, account support, events, and service inquiries.',
    tone: 'blue',
    metrics: [
      { label: 'Support Channels', value: '6' },
      { label: 'Avg Response', value: '< 4 hrs' },
      { label: 'Resolution Rate', value: '96%' },
      { label: 'Regional Offices', value: '8' },
    ],
    focusAreas: [
      { title: 'General Inquiries', description: 'Questions about platform usage, plans, or profile setup.' },
      { title: 'Partnership Desk', description: 'Assistance for partner onboarding and campaign planning.' },
      { title: 'Franchise Help', description: 'Guidance on franchise applications and operations.' },
      { title: 'Technical Support', description: 'Issue reporting for account, listings, and navigation.' },
    ],
    quickLinks: [
      { label: 'Membership Page', path: '/membership' },
      { label: 'Partner Page', path: '/partner' },
      { label: 'Franchise Page', path: '/franchise' },
      { label: 'Create Account', path: '/auth' },
    ],
    steps: [
      'Pick your inquiry type and preferred contact method.',
      'Share key details so the right team can triage quickly.',
      'Receive confirmation and expected response timeline.',
      'Track follow-ups until resolution is complete.',
    ],
    cta: {
      title: 'Need help from a specific team?',
      subtitle: 'Send your inquiry and we will route it to the correct department.',
      primary: { label: 'Send Inquiry', path: '/contact' },
      secondary: { label: 'Create Support Account', path: '/auth' },
    },
  },
  events: {
    eyebrow: 'Events',
    title: 'Events Calendar for Learning, Networking, and Growth',
    subtitle: 'Discover upcoming workshops, showcases, competitions, and networking sessions.',
    tone: 'indigo',
    metrics: [
      { label: 'Upcoming Events', value: '58' },
      { label: 'Monthly Attendees', value: '24K+' },
      { label: 'Cities Covered', value: '32' },
      { label: 'Online Sessions', value: '40%' },
    ],
    focusAreas: [
      { title: 'Workshops', description: 'Practical sessions for skill development and career growth.' },
      { title: 'Networking Events', description: 'Meet founders, leaders, and collaborators in your domain.' },
      { title: 'Competitions', description: 'Showcase talent and win recognition through curated contests.' },
      { title: 'Showcases', description: 'Explore project demos, performances, and partner activations.' },
    ],
    quickLinks: [
      { label: 'Featured Event Detail', path: '/events/nepal-talent-2026' },
      { label: 'Training Programs', path: '/training' },
      { label: 'Membership Access', path: '/membership' },
      { label: 'Register Account', path: '/auth' },
    ],
    steps: [
      'Browse events by category, date, and format.',
      'Register and secure attendance with profile verification.',
      'Attend sessions and collect participation points.',
      'Access follow-up resources and future event recommendations.',
    ],
    cta: {
      title: 'Join the next event cycle',
      subtitle: 'Register now to participate in high-impact community events.',
      primary: { label: 'Register Account', path: '/auth' },
      secondary: { label: 'View Membership', path: '/membership' },
    },
  },
  services: {
    eyebrow: 'Services',
    title: 'Service Ecosystem Across Lifestyle, Business, and Events',
    subtitle: 'Find trusted services from verified providers across equestrian, wellness, travel, events, and more.',
    tone: 'emerald',
    metrics: [
      { label: 'Service Categories', value: '7' },
      { label: 'Service Listings', value: '1.9K' },
      { label: 'Verified Providers', value: '620+' },
      { label: 'Avg Satisfaction', value: '4.8/5' },
    ],
    focusAreas: [
      { title: 'Category Discovery', description: 'Navigate services by category and use case.' },
      { title: 'Provider Trust', description: 'Work with verified providers and transparent quality standards.' },
      { title: 'Service Details', description: 'Review what is included, scope, and support options.' },
      { title: 'Booking Support', description: 'Get guided assistance for planning and scheduling.' },
    ],
    quickLinks: [
      { label: 'Equestrian Services', path: '/services/equestrian/horse-back-riding' },
      { label: 'Travel Services', path: '/services/travel' },
      { label: 'Event Management', path: '/services/events' },
      { label: 'Contact Service Desk', path: '/contact' },
    ],
    steps: [
      'Choose a category aligned to your service need.',
      'Compare offerings and provider credibility.',
      'Submit request or booking details.',
      'Coordinate delivery and post-service support.',
    ],
    cta: {
      title: 'Explore services by category',
      subtitle: 'Start with the category that matches your immediate goal.',
      primary: { label: 'Browse Categories', path: '/services' },
      secondary: { label: 'Contact Support', path: '/contact' },
    },
  },
};
